### ISSUE TITLE
Flow parameter arguments

### ISSUE THREAD

**Issue by kubik369** [Alexander-T-Moss/Small-Area-Flow-Comp#1]
The program has hard-coded compensation parameters now. Ideally, the program should either:

1. Have default parameters and accept different ones as arguments
2. Require the parameter arguments every time

The best option will depend on whether the model will have sane defaults in the end or not. I would recommend going with 1. for now.

**Comment by Alexander-T-Moss** [comment]
[V0.5.0](https://github.com/Alexander-T-Moss/Small-Area-Flow-Comp/releases/tag/v0.5.0)
