### ISSUE TITLE
Doesnt work with IdeaMaker gcodes

### ISSUE THREAD

**Issue by lordekeen** [Alexander-T-Moss/Small-Area-Flow-Comp#12]
Basically what the title says, it process the file, throws no errors and even show in the header that was processed, but theres no visible changes in the file aside from that header. I've looked at both unprocessed and processed files with Meld to compare. The file is here if you want a take a look: [https://pastebin.com/XTtSKpkK](url)

**Comment by Alexander-T-Moss** [comment]
To identify regions of gcode that correspond to regions of the print (top surfaces, perimeters, infill, etc.) the script looks for specific flags in the gcode. Currently the script only knows what PrusaSlicer/SuperSlicer and BambuStudio/OrcaSlicer flags to look like, so what is likely happening is that IdeaMaker are using a different format for the gcode flags, so when the script looks through the gcode, it doesn’t see any flags so never knows to start modifying sections of the gcode
