### ISSUE TITLE
Issue in Orca Slicer not exporting the changes

### ISSUE THREAD

**Issue by Needypoo** [Alexander-T-Moss/Small-Area-Flow-Comp#2]
I slice the file after adding the path to SmallAreaFlowComp_Win.exe "E:\OrcaSlicer-main\SmallAreaFlowComp_win.exe;"  to post processing scripts. I go to export it and a terminal pops up and then disappears. I then go to the gcode and search "old value" but it is not found.

**Comment by neeamradia** [comment]
Please include platform and slicer version. Didn’t download the script from the repo or is it the discord channel one?

**Comment by Needypoo** [comment]
I got it from both and they both resulted in the same.


![image](https://github.com/Alexander-T-Moss/Small-Area-Flow-Comp/assets/92352795/a9ef0fb8-d14a-4522-88f6-e460786f55ff)

![image](https://github.com/Alexander-T-Moss/Small-Area-Flow-Comp/assets/92352795/bb2a8dc9-f58a-4848-af88-3ef1cbfce58d)

**Comment by neeamradia** [comment]
Do you have any other slicer installs (SuSi? PS?) that you can test with to make sure it’s not an issue with your PC or the script ? Could be a slicer issue tho as I don’t think we tested fully with Orca

**Comment by Needypoo** [comment]
it does work in super slicer

**Comment by neeamradia** [comment]
Thank you. Could you send a screenshot of Orca where you have entered the path please?

**Comment by Needypoo** [comment]
![image](https://github.com/Alexander-T-Moss/Small-Area-Flow-Comp/assets/92352795/6e7fd755-19e1-41ce-b5ce-fa7cb0415e83)

**Comment by neeamradia** [comment]
Ok. This is definitely an orca specific issue. Might be to do with the way it labels extrusion roles etc or the way it handles post processing scripts or even the way it outputs gcode to post processing scripts. Does klipper estimator work on Orca? After this bit of investigation, I think it’s in Alex’s hands to find the problem / solve it as I don’t have much more ability here.

**Comment by Needypoo** [comment]
I am not sure but something funny i notice with Orca is it doesnt show how many layers are in the file.

**Comment by neeamradia** [comment]
Thank you. Could be an issue. I'll leave this to @Alexander-T-Moss now as this has reached the limit of my knowledge and ability.

**Comment by Alexander-T-Moss** [comment]
This should be something fairly easy to find, once I get the next revision out, debugging this will be a lot easier

**Comment by Alexander-T-Moss** [comment]
This issue should be resolved in [V0.5.1](https://github.com/Alexander-T-Moss/Small-Area-Flow-Comp/releases/tag/v0.5.1)

**Comment by neeamradia** [comment]
@Needypoo can you please confirm that this now works for you on OrcaSlicer?

**Comment by Needypoo** [comment]
![image](https://github.com/Alexander-T-Moss/Small-Area-Flow-Comp/assets/92352795/1dcac3d6-287c-4ae8-9329-f3670ca3e86f)
now with the latest one when trying to export gcode

**Comment by Needypoo** [comment]
nevermind it must have been the model.txt file. working!

**Comment by Alexander-T-Moss** [comment]
Okay, assuming this is working now I’ll close this issue :)
