### ISSUE TITLE
Ability to relocate log file

### ISSUE THREAD

**Issue by recrudesce** [Alexander-T-Moss/Small-Area-Flow-Comp#6]
If you put the script in a directory in `c:\program files` it fails with the log file writes.

Would be good if we could define where the log file goes ?
![image](https://github.com/Alexander-T-Moss/Small-Area-Flow-Comp/assets/6450799/ef93a840-9126-4c2c-8704-7951699c1d03)

For now I'll just move it somewhere it can write to :)

**Comment by Alexander-T-Moss** [comment]
Feature request noted, will be implemented in a future version of the script
