### ISSUE TITLE
Prusha slicer post prossing script doesn't exist 

### ISSUE THREAD

**Issue by Kern-Knight** [Alexander-T-Moss/Small-Area-Flow-Comp#9]
![17178346360381665997534173097494](https://github.com/Alexander-T-Moss/Small-Area-Flow-Comp/assets/172106900/7b147bb3-8594-4395-a1db-a895fb86cd5b)
![17178346699182326456550198264664](https://github.com/Alexander-T-Moss/Small-Area-Flow-Comp/assets/172106900/9a76ae2d-ae5e-4ec6-b63a-7e0770527366)
![17178346922598159694854711410258](https://github.com/Alexander-T-Moss/Small-Area-Flow-Comp/assets/172106900/0f974402-44a7-44b1-b3f4-627110813354)
Not sure what ive done wrong

**Comment by Alexander-T-Moss** [comment]
You might need to put quotation marks around the path name as it contains a space, or remove the space by putting the file in a place where the path won't contain a space

**Comment by Kern-Knight** [comment]
Ok cool ill try that
And get back to you
I did notice the space and was un sure as i only just learnt of this from a
youtuber

**Comment by Kern-Knight** [comment]
I did the location in "quotations" and it worked a tread thank you for your
help and time today appreciate it and love your work making 3d printing
better and more reliable

**Comment by Alexander-T-Moss** [comment]
Brilliant, glad that got it working for you, assuming all your issues are resolved I'll close this issue now, but feel free to re-open it or make another issues ticket if you need help with anything else, or something seems broken!
